# Generated by Django 5.0.5 on 2024-05-10 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
